version: '2'
services:
  java-app:
    image: wtf.small/bootstrap:0.1
    container_name: bootstrap-app
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - bootstrap-db
    command: ["./wait-for-it.sh", "bootstrap-db:5432", "--", "python", "app.py"]

  bootstrap-db:
    image: kiasaki/alpine-postgres:latest
    container_name: bootstrap-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres